### ISSUE TITLE
pkgnet throws an error for some R packages

### ISSUE THREAD

**Issue by bburns632** [UptakeOpenSource/pkgnet#95] opened 2018-05-01 04:30 UTC
This R-bloggers article notes an issue with pkgnet throwing an (very unhelpful) error:  https://www.r-bloggers.com/comparing-dependencies-of-popular-machine-learning-packages-with-pkgnet/

Some examples of packages throwing the error:
 tensorflow, randomFores, gbm

Error text: 
>Error in data.table::data.table(node = names(igraph::V(self$pkg_graph)), : column or argument 1 is NULL

**Comment by jameslamb** [comment] 2018-06-03 21:36
Hey I think I found the problem!! 

The version of `gbm` that's [on CRAN right now](https://cran.r-project.org/web/packages/gbm/index.html) has all of its dependencies in `Depends` instead of `Imports`.

We only check `Imports` (by default) and this was breaking because the package has no dependencies there. So `DependencyReporter` got an empty graph that we didn't catch. I am going to submit two separate PRs:

1. Make `c("Imports", "Depends")` the default behavior. `Depends` is the strongest form of dependency, so we should have always had it there.
2. Add cleaner handling of truly-empty graphs. We don't need to invent new test data for this...we can use `base` which we know won't have any dependencies!

reproducible examples:

**This fails with the error reported**

```r
reporter <- DependencyReporter$new(
    dep_types = "Imports"
)
reporter$set_package("gbm")

# Line that throws the error
reporter$graph_viz
```

**This works fine (or will in my PR coming soon)**

```
reporter <- DependencyReporter$new(
    dep_types = c("Imports", "Depends")
)
reporter$set_package("gbm")

# Line that throws the error
reporter$graph_viz
```

**Another example showing that the empty-graph thing is the problem**

```
reporter <- DependencyReporter$new(
    , dep_types = c("Imports", "Depends")
)
reporter$set_package("base")

# Line that throws the error
reporter$graph_viz
```

**Comment by jameslamb** [comment] 2018-06-03 22:52
Following up, this problem is NOT specific to `DependencyReporter`. It's generic to the problem of having an empty graph.

The `tensorflow` package (another one Shirin mentioned in her blog post) is all S3 methods: https://github.com/rstudio/tensorflow/blob/master/NAMESPACE

This _should_ be the code that breaks, although I wasn't  able to replicate the error

```
reporter <- FunctionReporter$new()
reporter$set_package("tensorflow")
reporter$graph_viz
```

**Comment by jameslamb** [comment] 2018-06-03 23:40
Looking through this some more, I still can not reproduce the error for `tensorflow`. The more I think about it, it should be impossible for `FunctionReporter` to get an empty graph. We called it `FunctionReporter` but in reality it's `ObjectReporter`. S3 methods, lists, whatever all work.

**Comment by jameslamb** [comment] 2018-06-03 23:43
#99 is the second PR addressing this. I think if we close all my open PRs, we'll be able to call this issue done.

**Comment by jameslamb** [comment] 2018-06-10 21:37
Just tested with the newest master. Comfortable closing this!

All of the below worked

```
library(pkgnet)
CreatePackageReport('gbm')
CreatePackageReport('tensorflow')
CreatePackageReport('randomForest')
```

^ note that these all work with the recent version _on CRAN_. Did not try dev versions of the package.

Thanks again for reporting this @ShirinG ! We will try to get out a release with these fixes soon!

**Closed by jameslamb** 2018-06-10 21:37 UTC
Labels: bug, help wanted
