### ISSUE TITLE
CreatePackageReport creates the report in /Library instead of the current working directory

### ISSUE THREAD

**Issue by mfrasco6** [UptakeOpenSource/pkgnet#78] opened 2018-04-13 21:49 UTC
When I evaluate `CreatePackageReport` with the default argument for `report_path`, it saves the output within the `/Library/Frameworks/R.framework/Versions/3.4/Resources/library/pkgnet/package_report/` directory on my machine.

I think the issue is that the `getwd()` call that is supplied to `report_path` is not being evaluated within the calling environment. This suspicion was confirmed when I passed a string literal to `report_path`, as the html report was generated in the correct location.

**Comment by jameslamb** [comment] 2018-04-14 04:12
ah! I was able to reproduce this tonight, thank you! We will get it fixed ASAP

**Comment by s-fleck** [comment] 2018-04-24 06:06
It would be even better to create the report in a tempfile() instead of the current working directory if the user supplies no report_path. I think its against CRAN guidelines to have functions write to the user filespace by default. I was not able to find any information on that in the documentation, but I got a complaint by the CRAN team for one of my packages once.

**Comment by jameslamb** [comment] 2018-04-26 04:12
@s-fleck Can you elaborate on that? This report is the main output of the `CreatePackageReport` function. Our assumption was that you'd generate this file and be able to use it in code reviews.

So far, the only complaint we've gotten from CRAN is about writing to that reserved location (not writing to disk in general), so I think maybe we are ok?

I'd be curious to see the feedback you got from the CRAN team. There are packages on CRAN like `BigMemory` whose explicit promise is "we will write a bunch of stuff to disk for you and you don't need to think about it". So I wonder if there is actually a policy against it but they got an exception because using that package is basically opting in to using local disk?

**Comment by jameslamb** [comment] 2018-11-06 03:43
Coming back to this. @s-fleck @mfrasco I'm happy to report that we can close this issue.

Fixes to where files get written: #92 , #109 
Fixes to write all our stuff to a `tempdir()`: #108

**Closed by jameslamb** 2018-11-06 03:43 UTC
Labels: bug, good first issue
